"use client"

import { FormEvent, useEffect, useState } from 'react'
import { BarChart3, BookOpen, CheckCircle2, ClipboardList, GraduationCap, ListTodo, Plus, Users } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

type Course = { id: string; code: string; name: string; schedule: string | null; room: string | null; enrollments: Array<{ id: string; student: { studentId: string; user: { firstName: string; lastName: string; email: string } } }>; assignments: Array<{ id: string; title: string; dueDate: string; maxPoints: number; submissions: Array<{ id: string; grade: number | null; feedback: string | null; student: { studentId: string; user: { firstName: string; lastName: string } } }> }> }
type Dashboard = { employeeId: string; courses: Course[]; courseSummaries: Array<{ id: string; code: string; name: string; credits: number; schedule: string | null; room: string | null; enrollmentCount: number; assignmentCount: number; pendingSubmissions: number }>; lessonPlans: Array<{ id: string; title: string; objectives: string; content: string; week: number | null; plannedDate: string | null; status: string; course: { code: string; name: string } }>; todos: Array<{ id: string; title: string; dueDate: string | null; isCompleted: boolean }>; grades: Array<{ id: string; grade: string; gradePoint: number; courseId: string; student: { studentId: string; user: { firstName: string; lastName: string } } }>; analytics: { totalStudents: number; gradedRecords: number; averageGradePoint: number } }
const date = (value: string | null) => value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : 'No due date'

export function TeacherDashboard({ firstName }: { firstName: string }) {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); const [tab, setTab] = useState<'classes' | 'assignments' | 'analytics' | 'plans' | 'todos'>('classes'); const [selectedCourse, setSelectedCourse] = useState(''); const [saving, setSaving] = useState(false)
  const load = async () => { const token = localStorage.getItem('accessToken'); if (!token) return; try { const response = await fetch('/api/teachers/me', { headers: { Authorization: `Bearer ${token}` } }); const result = await response.json(); if (!response.ok) throw new Error(result?.error?.message || 'Unable to load your dashboard.'); setData(result.teacher); setSelectedCourse((current) => current || result.teacher.courses[0]?.id || '') } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load your dashboard.') } }
  useEffect(() => { load() }, [])
  const action = async (body: Record<string, unknown>) => { const token = localStorage.getItem('accessToken'); if (!token) return false; setSaving(true); setError(''); try { const response = await fetch('/api/teachers/me', { method: body.action === 'toggleTodo' || body.action === 'gradeSubmission' ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result?.error?.message || 'Unable to save your change.'); await load(); return true } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save your change.'); return false } finally { setSaving(false) } }
  if (!data) return error ? <p className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p> : <p className="py-12 text-center text-gray-500">Loading your teaching workspace…</p>
  const tabs = [['classes', 'Classes & Rosters', Users], ['assignments', 'Assignment Center', ClipboardList], ['analytics', 'Performance Analytics', BarChart3], ['plans', 'Lesson Plans', BookOpen], ['todos', 'To-Do List', ListTodo]] as const
  const course = data.courses.find((item) => item.id === selectedCourse)
  return <div className="space-y-6"><section className="rounded-2xl bg-gradient-to-br from-royal-900 via-royal-700 to-royal-600 p-6 text-white shadow-lg sm:p-8"><p className="text-sm font-medium text-gold-300">TEACHING WORKSPACE</p><h1 className="mt-2 text-3xl font-bold font-heading">Welcome back, {firstName}.</h1><p className="mt-3 text-royal-100">Employee ID: {data.employeeId} · Manage your classes, learners, and instructional work in one place.</p></section>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="p-5"><p className="text-sm text-gray-500">My Classes</p><p className="text-3xl font-bold">{data.courses.length}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-gray-500">Students</p><p className="text-3xl font-bold">{data.analytics.totalStudents}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-gray-500">Pending grading</p><p className="text-3xl font-bold">{data.courseSummaries.reduce((sum, item) => sum + item.pendingSubmissions, 0)}</p></CardContent></Card></section><div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([id, label, Icon]) => <Button key={id} variant={tab === id ? 'default' : 'outline'} className="shrink-0" onClick={() => setTab(id)}><Icon className="mr-2 h-4 w-4" />{label}</Button>)}</div>
    {tab === 'classes' && <Card><CardHeader><CardTitle>Class & Student Rosters</CardTitle></CardHeader><CardContent><div className="grid gap-4 lg:grid-cols-[18rem_1fr]"><div className="space-y-2">{data.courseSummaries.map((item) => <button key={item.id} onClick={() => setSelectedCourse(item.id)} className={`w-full rounded-lg p-3 text-left ${selectedCourse === item.id ? 'bg-royal-600 text-white' : 'bg-gray-50 dark:bg-gray-800'}`}><p className="font-semibold">{item.code}</p><p className="text-sm">{item.name}</p><p className="mt-1 text-xs opacity-80">{item.enrollmentCount} students · {item.room || 'Room TBA'}</p></button>)}</div><div>{course ? <><h3 className="text-lg font-semibold">{course.code} · {course.name}</h3><p className="mb-4 text-sm text-gray-500">{course.schedule || 'Schedule TBA'}{course.room ? ` · ${course.room}` : ''}</p>{course.enrollments.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-gray-500"><th className="p-2">Student</th><th className="p-2">Student ID</th><th className="p-2">Email</th></tr></thead><tbody>{course.enrollments.map(({ id, student }) => <tr key={id} className="border-b"><td className="p-2 font-medium">{student.user.firstName} {student.user.lastName}</td><td className="p-2">{student.studentId}</td><td className="p-2">{student.user.email}</td></tr>)}</tbody></table></div> : <p className="text-sm text-gray-500">No students are enrolled in this class.</p>}</> : <p className="text-gray-500">No classes are assigned to your account yet.</p>}</div></div></CardContent></Card>}
    {tab === 'assignments' && <div className="grid gap-6 lg:grid-cols-2"><AssignmentForm courses={data.courses} saving={saving} onSave={action} /> <Card><CardHeader><CardTitle>Assignments & Submissions</CardTitle></CardHeader><CardContent className="space-y-4">{data.courses.flatMap((item) => item.assignments.map((assignment) => <div key={assignment.id} className="rounded-lg border p-3"><p className="font-semibold">{item.code} · {assignment.title}</p><p className="mb-2 text-sm text-gray-500">Due {date(assignment.dueDate)} · {assignment.maxPoints} points · {assignment.submissions.length} submissions</p>{assignment.submissions.map((submission) => <GradeSubmission key={submission.id} submission={submission} maxPoints={assignment.maxPoints} saving={saving} onSave={action} />)}</div>))}{!data.courses.some((item) => item.assignments.length) && <p className="text-sm text-gray-500">Create your first assignment using the form.</p>}</CardContent></Card></div>}
    {tab === 'analytics' && <Card><CardHeader><CardTitle>Performance Analytics</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-3"><Metric label="Average grade point" value={data.analytics.averageGradePoint.toFixed(2)} /><Metric label="Published grade records" value={String(data.analytics.gradedRecords)} /><Metric label="Students across classes" value={String(data.analytics.totalStudents)} /></div><div className="mt-6 space-y-3">{data.courseSummaries.map((item) => { const grades = data.grades.filter((grade) => grade.courseId === item.id); const avg = grades.length ? grades.reduce((sum, grade) => sum + grade.gradePoint, 0) / grades.length : 0; return <div key={item.id} className="rounded-lg bg-gray-50 p-4 dark:bg-gray-800"><div className="flex justify-between"><strong>{item.code} · {item.name}</strong><span>{grades.length ? `Average ${avg.toFixed(2)}` : 'No grades published'}</span></div><div className="mt-2 h-2 rounded-full bg-gray-200"><div className="h-2 rounded-full bg-royal-600" style={{ width: `${Math.min(avg / 4 * 100, 100)}%` }} /></div></div> })}</div></CardContent></Card>}
    {tab === 'plans' && <div className="grid gap-6 lg:grid-cols-2"><LessonPlanForm courses={data.courses} saving={saving} onSave={action} /><Card><CardHeader><CardTitle>Plans & Pacing Guides</CardTitle></CardHeader><CardContent className="space-y-3">{data.lessonPlans.length ? data.lessonPlans.map((plan) => <div key={plan.id} className="rounded-lg border p-3"><p className="font-semibold">{plan.course.code} · {plan.title}</p><p className="text-sm text-gray-500">Week {plan.week || '—'} · {date(plan.plannedDate)} · {plan.status}</p><p className="mt-2 text-sm"><strong>Objectives:</strong> {plan.objectives}</p></div>) : <p className="text-sm text-gray-500">No lesson plans have been added yet.</p>}</CardContent></Card></div>}
    {tab === 'todos' && <div className="grid gap-6 lg:grid-cols-2"><TodoForm saving={saving} onSave={action} /><Card><CardHeader><CardTitle>To-Do List & Reminders</CardTitle></CardHeader><CardContent className="space-y-2">{data.todos.length ? data.todos.map((todo) => <label key={todo.id} className="flex cursor-pointer items-center gap-3 rounded-lg border p-3"><input type="checkbox" checked={todo.isCompleted} disabled={saving} onChange={(event) => action({ action: 'toggleTodo', todoId: todo.id, completed: event.target.checked })} /><span className={todo.isCompleted ? 'flex-1 text-gray-400 line-through' : 'flex-1'}>{todo.title}<small className="ml-2 text-gray-500">{date(todo.dueDate)}</small></span></label>) : <p className="text-sm text-gray-500">Your list is clear.</p>}</CardContent></Card></div>}</div>
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-gray-50 p-4 dark:bg-gray-800"><p className="text-sm text-gray-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div> }
function AssignmentForm({ courses, saving, onSave }: { courses: Course[]; saving: boolean; onSave: (data: Record<string, unknown>) => Promise<boolean> }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await onSave({ action: 'createAssignment', courseId: form.get('courseId'), title: form.get('title'), description: form.get('description'), dueDate: form.get('dueDate'), maxPoints: form.get('maxPoints'), fileUrl: form.get('fileUrl') })) event.currentTarget.reset() }; return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="h-5 w-5" />Create assignment</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={submit}><select required name="courseId" className="h-10 w-full rounded-md border bg-background px-3"><option value="">Choose class</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.code} · {course.name}</option>)}</select><input required name="title" placeholder="Assignment title" className="h-10 w-full rounded-md border bg-background px-3" /><textarea required name="description" placeholder="Instructions" className="min-h-24 w-full rounded-md border bg-background p-3" /><div className="grid gap-3 sm:grid-cols-2"><input required type="datetime-local" name="dueDate" className="h-10 rounded-md border bg-background px-3" /><input required type="number" min="1" name="maxPoints" placeholder="Points" className="h-10 rounded-md border bg-background px-3" /></div><input name="fileUrl" type="url" placeholder="Material link (optional)" className="h-10 w-full rounded-md border bg-background px-3" /><Button disabled={saving}>Create assignment</Button></form></CardContent></Card> }
function GradeSubmission({ submission, maxPoints, saving, onSave }: { submission: Course['assignments'][number]['submissions'][number]; maxPoints: number; saving: boolean; onSave: (data: Record<string, unknown>) => Promise<boolean> }) { const [grade, setGrade] = useState(submission.grade?.toString() || ''); const [feedback, setFeedback] = useState(submission.feedback || ''); return <div className="mt-2 rounded bg-gray-50 p-2 text-sm dark:bg-gray-800"><p>{submission.student.user.firstName} {submission.student.user.lastName} <span className="text-gray-500">({submission.student.studentId})</span></p><div className="mt-2 flex gap-2"><input value={grade} onChange={(event) => setGrade(event.target.value)} type="number" min="0" max={maxPoints} placeholder="Score" className="h-8 w-20 rounded border bg-background px-2" /><input value={feedback} onChange={(event) => setFeedback(event.target.value)} placeholder="Feedback" className="h-8 flex-1 rounded border bg-background px-2" /><Button size="sm" disabled={saving || grade === ''} onClick={() => onSave({ action: 'gradeSubmission', submissionId: submission.id, grade: Number(grade), feedback })}>Save</Button></div></div> }
function LessonPlanForm({ courses, saving, onSave }: { courses: Course[]; saving: boolean; onSave: (data: Record<string, unknown>) => Promise<boolean> }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await onSave({ action: 'createLessonPlan', courseId: form.get('courseId'), title: form.get('title'), objectives: form.get('objectives'), content: form.get('content'), week: form.get('week'), plannedDate: form.get('plannedDate') })) event.currentTarget.reset() }; return <Card><CardHeader><CardTitle>Create lesson plan</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={submit}><select required name="courseId" className="h-10 w-full rounded-md border bg-background px-3"><option value="">Choose class</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.code}</option>)}</select><input required name="title" placeholder="Lesson title" className="h-10 w-full rounded-md border bg-background px-3" /><textarea required name="objectives" placeholder="Learning objectives" className="min-h-20 w-full rounded-md border bg-background p-3" /><textarea required name="content" placeholder="Activities, resources, and pacing notes" className="min-h-24 w-full rounded-md border bg-background p-3" /><div className="grid gap-3 sm:grid-cols-2"><input name="week" type="number" min="1" placeholder="Week" className="h-10 rounded-md border bg-background px-3" /><input name="plannedDate" type="date" className="h-10 rounded-md border bg-background px-3" /></div><Button disabled={saving}>Save plan</Button></form></CardContent></Card> }
function TodoForm({ saving, onSave }: { saving: boolean; onSave: (data: Record<string, unknown>) => Promise<boolean> }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await onSave({ action: 'createTodo', title: form.get('title'), dueDate: form.get('dueDate') })) event.currentTarget.reset() }; return <Card><CardHeader><CardTitle>Add reminder</CardTitle></CardHeader><CardContent><form className="flex flex-col gap-3 sm:flex-row" onSubmit={submit}><input required name="title" placeholder="e.g. Review HIST 201 submissions" className="h-10 flex-1 rounded-md border bg-background px-3" /><input name="dueDate" type="date" className="h-10 rounded-md border bg-background px-3" /><Button disabled={saving}><CheckCircle2 className="mr-2 h-4 w-4" />Add task</Button></form></CardContent></Card> }
