INSERT INTO "Course" (id, code, name, description, credits, "departmentId", semester, level, "isActive", "createdAt", "updatedAt")
VALUES
  (concat('catalog-', 'CCS101'), 'CCS101', 'Introduction to Cross-Cultural Studies', 'Understanding culture; cultural identity; globalization; cultural diversity', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 1, 1, true, NOW(), NOW()),
  (concat('catalog-', 'CCS102'), 'CCS102', 'Intercultural Communication', 'Verbal and non-verbal communication; communication across cultures; conflict resolution; cross-cultural negotiation', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 1, 1, true, NOW(), NOW()),
  (concat('catalog-', 'CCS103'), 'CCS103', 'Cultural Anthropology', 'Human societies; traditions and customs; kinship and family systems; indigenous cultures', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 1, 1, true, NOW(), NOW()),
  (concat('catalog-', 'CCS104'), 'CCS104', 'Sociology of Culture', 'Social structures; race and ethnicity; social inequality; cultural change', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 1, 1, true, NOW(), NOW()),
  (concat('catalog-', 'CCS105'), 'CCS105', 'World Religions', 'Christianity; Islam; Hinduism; Buddhism; African Traditional Religions; Judaism', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 1, 1, true, NOW(), NOW()),
  (concat('catalog-', 'CCS201'), 'CCS201', 'Global Studies', 'International relations; global development; migration; human rights', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 2, 2, true, NOW(), NOW()),
  (concat('catalog-', 'CCS202'), 'CCS202', 'Comparative Cultures', 'African cultures; Asian cultures; European cultures; American cultures; Middle Eastern cultures', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 2, 2, true, NOW(), NOW()),
  (concat('catalog-', 'CCS203'), 'CCS203', 'Language and Society', 'Sociolinguistics; multilingualism; language and identity; translation studies', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 2, 2, true, NOW(), NOW()),
  (concat('catalog-', 'CCS204'), 'CCS204', 'Cross-Cultural Psychology', 'Human behavior across cultures; personality differences; mental health in different societies; cultural influences on learning', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 2, 2, true, NOW(), NOW()),
  (concat('catalog-', 'CCS205'), 'CCS205', 'International Business and Culture', 'Business etiquette; global marketing; international management; consumer behavior', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 2, 2, true, NOW(), NOW()),
  (concat('catalog-', 'CCS301'), 'CCS301', 'Peace and Conflict Studies', 'Mediation; peacebuilding; international conflicts; reconciliation', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 3, 3, true, NOW(), NOW()),
  (concat('catalog-', 'CCS302'), 'CCS302', 'Gender and Culture', 'Gender roles; women''s studies; masculinity studies; LGBTQ+ issues in different cultures', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 3, 3, true, NOW(), NOW()),
  (concat('catalog-', 'CCS303'), 'CCS303', 'Migration and Diaspora Studies', 'Refugees; immigration; cultural adaptation; integration', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 3, 3, true, NOW(), NOW()),
  (concat('catalog-', 'CCS304'), 'CCS304', 'African Studies', 'African history; African politics; African literature; African philosophy', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 3, 3, true, NOW(), NOW()),
  (concat('catalog-', 'CCS305'), 'CCS305', 'Research Methods', 'Qualitative research; interviews; surveys; ethnography; data analysis', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 3, 3, true, NOW(), NOW()),
  (concat('catalog-', 'CCS401'), 'CCS401', 'Ethics and Cultural Diversity', 'Human dignity; cultural sensitivity; professional ethics; social responsibility', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 4, 4, true, NOW(), NOW()),
  (concat('catalog-', 'CCS402'), 'CCS402', 'Foreign Languages', 'French; Spanish; Arabic; Chinese; German; Swahili', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 4, 4, true, NOW(), NOW()),
  (concat('catalog-', 'CCS403'), 'CCS403', 'History of Civilizations', 'Ancient civilizations; colonialism; post-colonial studies; modern world history', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 4, 4, true, NOW(), NOW()),
  (concat('catalog-', 'CCS404'), 'CCS404', 'International Development', 'Sustainable development; poverty reduction; NGOs; community development', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 4, 4, true, NOW(), NOW()),
  (concat('catalog-', 'CCS405'), 'CCS405', 'Capstone Project or Thesis', 'Independent research; fieldwork; internship; final dissertation', 3, (SELECT id FROM "Department" ORDER BY "createdAt" LIMIT 1), 4, 4, true, NOW(), NOW())
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, credits = EXCLUDED.credits, semester = EXCLUDED.semester, level = EXCLUDED.level, "isActive" = true, "updatedAt" = NOW();
